### PR TITLE
internal/protocol: Default timeout for Call

### LINKED ISSUE #235: Add a default timeout for Connector.Connect
Juju has occasion to change the bind address of the initial Dqlite node upon entering HA.

When this happens, existing connections keep trying to connect, with our logs repeated output like this:
```
2023-03-09 08:57:14 WARNING juju.worker.dbaccessor connector.go:77 attempt 2507: server 127.0.0.1:17666: dial: dial tcp 127.0.0.1:17666: connect: connection refused
2023-03-09 08:57:14 WARNING juju.worker.dbaccessor connector.go:77 attempt 2507: server 127.0.0.1:17666: dial: dial tcp 127.0.0.1:17666: connect: connection refused
2023-03-09 08:57:15 WARNING juju.worker.dbaccessor connector.go:77 attempt 2508: server 127.0.0.1:17666: dial: dial tcp 127.0.0.1:17666: connect: connection refused
2023-03-09 08:57:15 WARNING juju.worker.dbaccessor connector.go:77 attempt 2508: server 127.0.0.1:17666: dial: dial tcp 127.0.0.1:17666: connect: connection refused
```

An existing call to `Exec` is locked up at this point:
```
#       0x46a8d4        time.Sleep+0x134                                                                /u
sr/local/go/src/runtime/time.go:195
#       0x1c14f28       github.com/canonical/go-dqlite/internal/protocol.makeRetryStrategies.func1+0x48 /h
ome/joseph/go/pkg/mod/github.com/canonical/go-dqlite@v1.11.5/internal/protocol/connector.go:321
#       0x1c12799       github.com/Rican7/retry.shouldAttempt+0x39                                      /h
ome/joseph/go/pkg/mod/github.com/!rican7/retry@v0.3.1/retry.go:32
#       0x1c126f6       github.com/Rican7/retry.Retry+0x96                                              /h
ome/joseph/go/pkg/mod/github.com/!rican7/retry@v0.3.1/retry.go:19
#       0x1c131c4       github.com/canonical/go-dqlite/internal/protocol.(*Connector).Connect+0xa4      /h
ome/joseph/go/pkg/mod/github.com/canonical/go-dqlite@v1.11.5/internal/protocol/connector.go:74
#       0x1c42628       github.com/canonical/go-dqlite/driver.(*Connector).Connect+0x268                /h
ome/joseph/go/pkg/mod/github.com/canonical/go-dqlite@v1.11.5/driver/driver.go:261
#       0x1c05d22       database/sql.(*DB).conn+0x762                                                   /u
sr/local/go/src/database/sql/sql.go:1393
#       0x1c0ce52       database/sql.(*Stmt).connStmt+0x252                                             /u
sr/local/go/src/database/sql/sql.go:2724
#       0x1c0c364       database/sql.(*Stmt).ExecContext+0x184                                          /u
sr/local/go/src/database/sql/sql.go:2628
#       0x46e7204       database/sql.(*Stmt).Exec+0x44                                                  /u
sr/local/go/src/database/sql/sql.go:2651
```

This is problematic given Juju's architecture, because our worker loops can be blocked from actually shutting down.

Particularly bad is that this happens with `db.Ping`, which we use for health checks.

### PR DESCRIPTION
**Pull request by cole-miller**
This implements the suggestion to have a default or "fallback" timeout for calls to `protocol.Connector.Connect()` in #235. The fallback timeout of 30 seconds is used only if the passed context does not already have a deadline configured.

Closes #235 

Signed-off-by: Cole Miller <cole.miller@canonical.com>

### CODE REVIEW

**Review by MathieuBordere — APPROVED** [review]
Can you please just double check if we don't have any logic ourselves that depends on this function retrying forever?

**Review by manadart — COMMENTED** [review]
I think the issue was actually manifest after the connection was established, then subsequently lost.

If you look at `Query` versus `QueryContext` for example, they fall through to [protocol.Call](https://github.com/canonical/go-dqlite/blob/master/internal/protocol/protocol.go#L35), where it conditionally sets the `conn` deadline [here](https://github.com/canonical/go-dqlite/blob/master/internal/protocol/protocol.go#L58).

This is probably where we should also be setting a fall-back.

**Comment by cole-miller** [comment]
@manadart Thanks, I guess I got my wires crossed interpreting that issue thread. Let me confirm that updating the `Call` logic makes sense and I'll push v2.

**Comment by cole-miller** [comment]
Okay, the latest commit sets a default deadline for Call instead of for Connect.

**Pull request closed without merging**
