### PR TITLE
proxy: make socketpair fds close-on-exec

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Looks like it's breaking stuff?
https://travis-ci.org/github/canonical/go-dqlite/builds/747647106

**Comment by brauner** [comment]
> Looks like it's breaking stuff?
> https://travis-ci.org/github/canonical/go-dqlite/builds/747647106

Where and how is that code relying on these sockets to be inheritable via exec is what I'd like to know?

**Comment by freeekanayaka** [comment]
> > Looks like it's breaking stuff?
> > https://travis-ci.org/github/canonical/go-dqlite/builds/747647106
> 
> Where and how is that code relying on these sockets to be inheritable via exec is what I'd like to know?

I don't think we rely on it, it might be just a test issue.

**Comment by freeekanayaka** [comment]
It seems that the unit test that has failed in the Travis run is unrelated to this change (in fact that test doesn't even use the `app` package), and the rest of the errors are likely caused by that unit test failing and not properly cleaning up.

Unfortunately I believe Travis has removed the ability to trigger a new test run for the same job.

**Comment by freeekanayaka** [comment]
I've created a test PR with the same changeset as here to trigger another Travis build here https://travis-ci.org/github/canonical/go-dqlite/builds/748127567

It's queued atm, let's see.

**Comment by freeekanayaka** [comment]
I got again the same failure, so I'm wondering if there's some kind of regression or change, unrelated to this PR.

**Comment by brauner** [comment]
Can someone retrigger this pr to see whether the failure was a fluke or whether we need to take this more seriously?

**Comment by stgraber** [comment]
@brauner can you do a no change push (git commit --amend && git push --force)?

We moved to travis.com now so I can't easily retrigger since the current run was on .org

**Comment by brauner** [comment]
> @brauner can you do a no change push (git commit --amend && git push --force)?
> 
> We moved to travis.com now so I can't easily retrigger since the current run was on .org

Done!

**Comment by brauner** [comment]
Doesn't look like Travis even ran?

**Comment by stgraber** [comment]
```

        Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.
```

**Pull request closed without merging**
