### PR TITLE
node: Document usage of ReconfigureMembership and ReconfigureMembershipExt

### LINKED ISSUE #298: Better documentation for `ReconfigureMembership`
See https://github.com/canonical/lxd/issues/13524; it would be nice if the docs for `ReconfigureMembership` and `ReconfigureMembershipExt` included the usage instructions from the [dqlite header file](https://github.com/canonical/dqlite/blob/v1.16.4/include/dqlite.h#L575).

### PR DESCRIPTION
**Pull request by cole-miller**
Closes #298.

Signed-off-by: Cole Miller <cole.miller@canonical.com>

### CODE REVIEW

**Review by just-now — APPROVED** [review]
Looks good.

**Comment by cole-miller** [comment]
Made some edits, thanks @letFunny for the feedback offline.

**Comment by cole-miller** [comment]
Something going on with coveralls...

**Review by letFunny — APPROVED** [review]
Thanks Cole, LGTM once the CI is passing!

**Pull request merged**
