### PR TITLE
Set protocol version inside connectAttemptOne

### PR DESCRIPTION
**Pull request by cnnrznn**
I am working on https://github.com/canonical/go-dqlite/issues/134

The PR I have to resolve that issue is cleaner if I first push setting of the protocol version down into `connectAttemptOne` from `connectAttemptAll`.

Consider merging this before I rebase and submit a PR for #134

### CODE REVIEW

**Comment by cnnrznn** [comment]
@cole-miller thoughts on this?

**Comment by cole-miller** [comment]
Sorry @cnnrznn, I was on PTO Friday through Monday. I'm going to wait for CI to pass but once it does this looks good -- thanks for the contribution, keep them coming!

**Comment by cnnrznn** [comment]
No rush!

I saw you merged the dependency fix PR. Hopefully these tests pass now.

**Comment by cnnrznn** [comment]
When they were failing after I saw that the action is still trying to pull in the raft-dev lib.

@cole-miller if you're manually kicking these off it's fine to leave it until tomorrow. It can wait :)

**Comment by cnnrznn** [comment]
@cole-miller I rebased this commit on `go-dqlite/master`. Instinct tells me this might fix the out-of-date workflow file but it doesn't make sense to me why

**Comment by cnnrznn** [comment]
:rocket:

**Pull request merged**
