### PR TITLE
Swap my-key and my-value

### PR DESCRIPTION
**Pull request by snoe925**
While the examples work, this I think is better documentation.

### CODE REVIEW

**Comment by MathieuBordere** [comment]
Hi @snoe925,

Thanks for this!
Canonical requires contributors to sign the Canonical CLA https://ubuntu.com/legal/contributors, you only have to do it once and afterwards you can contribute to any Canonical project in the future.

Cheers

**Comment by snoe925** [comment]
I signed the CLA.

**Comment by MathieuBordere** [comment]
> I signed the CLA.

Thanks, the check still fails, but we might need to give it some time until it trickles through. I'll keep an eye on it.

**Comment by stgraber** [comment]
```
- snoe925 ✓ (has signed the CLA)
```
All good now. I suspect the issue was that someone had to manually invite @snoe925 to the Github organization used to keep track of it.

**Comment by stgraber** [comment]
Thanks @snoe925 for your contribution!
Sorry about the bumpiness with that CLA, any further contribution will be much easier and faster!

**Pull request merged**
