### PR TITLE
Drop references to libco

### PR DESCRIPTION
**Pull request by freeekanayaka**

### CODE REVIEW

**Comment by freeekanayaka** [comment]
Need to update the libdqlite deb package in the PPA to fix the build.

**Comment by AlexAndrascu** [comment]
> Need to update the libdqlite deb package in the PPA to fix the build.

Imna start cleaning up all the libco references from the Dockerfile and recommit then

**Comment by freeekanayaka** [comment]
There's a bit of a chicken-and-egg problem here: the dqlite deb package in the PPA won't build until we merge this branch, because that package also builds the dqlite demo by pulling go-dqlite, which at the moment doesn't compile.

**Comment by freeekanayaka** [comment]
@stgraber @brauner please could you go ahead and merge this branch even if Travis is red? I will then re-trigger the PPA package build and at that point a new run on master should be green.

**Pull request merged**
