### PR TITLE
refactor: allow any net.Conn works with dqlite

### PR DESCRIPTION
**Pull request by Zxilly**
Close: #238 

For now, although dqlite accepts any connection that matches `net.Conn`, it only works if the target is tcp.Conn or tls.Conn.

Also, dqlite assumes that users always use `websocket` to communicate, which again limits the flexibility when used as a library.

This patch maintains the previous behavior for tcp and tls, while allowing other constructs that implement the `net.Conn` interface to work properly.

### CODE REVIEW

**Comment by freeekanayaka** [comment]
Not a hard blocker, but it would be nice to add a unit test for this, ideally using quic. I believe it shouldn't be too much difficult.

**Comment by MathieuBordere** [comment]
Thanks for this @Zxilly! Can I ask you to sign the [Canonical CLA](https://ubuntu.com/legal/contributors/agreement) please? It's a one time thing, afterwards you can contribute to any Canonical project.

**Comment by Zxilly** [comment]
I have signed CLA, currently I'm working a unit test.

**Comment by freeekanayaka** [comment]
> Seems quic go can not run with go 1.13. Maybe we should use named pipe？

Ah too bad. Is there an easy way to run that test only with go >= 1.19? If not, then yeah, perhaps using something like named pipe would be ok.

**Comment by Zxilly** [comment]
I split test code to make it only compiled on higher version.

For indirectly dependencies I have no good idea. A possible solution can be require a empty package and replace it with real quic-go. With this, the quic-go won't be part of dqlite dependencies.

**Comment by freeekanayaka** [comment]
Thanks @Zxilly, tests are still failing, but the overall testing approach looks good to me.

**Comment by Zxilly** [comment]
I dive into deps dependencies, seems `quic-go` relies on `golang.org/x/sys@v0.5.0`, which need go 1.17 to compile.
I just commented quic test and add another pipe implementation. If one day dqlite set its go version to 1.17+, it can be re-enabled.

**Pull request merged**
